import { Users, Dog, CalendarClock } from 'lucide-react';
import type { Tour } from '../../../../contexts/TourContext';

export const TOURS: Tour[] = [
  {
    id: 'clients',
    name: 'Register a client',
    icon: Users,
    description: 'Walk through every part of the client record — from names to GPS, credit limits, and notes.',
    steps: [
      {
        target: 'nav-clients',
        title: 'Clients live here',
        body: 'The Clients module holds every pet owner. Click the sidebar entry to open it.',
        placement: 'right',
        navigateTo: 'clients',
      },
      {
        target: 'clients-register',
        title: 'Register a new client',
        body: 'Use this button to start a fresh client record. You can also bulk-import from CSV later.',
        placement: 'bottom',
      },
      {
        target: 'client-form-firstname',
        title: 'Names go here',
        body: 'First name + surname are required. Title and second name are optional but helpful for greetings on invoices.',
        placement: 'bottom',
        navigateTo: 'register-client',
        waitMs: 200,
      },
      {
        target: 'client-form-contact',
        title: 'How to reach them',
        body: 'Email and phone power appointment reminders, invoices, and the in-app messaging thread for this client.',
        placement: 'bottom',
      },
      {
        target: 'client-form-demographics',
        title: 'Gender, region & birthday',
        body: 'Region tailors greetings and reporting; date of birth lets you spot long-standing clients and send birthday notes.',
        placement: 'top',
      },
      {
        target: 'client-form-address',
        title: 'Street address',
        body: 'The physical address — estate / road / town. It prints on invoices and is the starting point for house-call visits, so be as specific as you can (e.g. "Westlands, Nairobi").',
        placement: 'top',
      },
      {
        target: 'client-form-location',
        title: 'Pin them on the map (GPS)',
        body: 'Go beyond the street: drop a pin on the map, type exact latitude/longitude, or hit "Use My Location". These precise coordinates power house-call routing and area reports — the street address alone can\'t.',
        placement: 'left',
      },
      {
        target: 'client-form-risk',
        title: 'Risk & credit',
        body: 'Flag the client type, set a max debt ceiling, and score their payment risk — this drives credit warnings at checkout.',
        placement: 'left',
        optional: true,
      },
      {
        target: 'client-form-notes',
        title: 'Internal notes',
        body: 'Private reminders only staff can see — allergies to handling, preferred vet, anything worth flagging next visit.',
        placement: 'top',
        optional: true,
      },
      {
        target: 'client-form-submit',
        title: 'Save the client',
        body: 'Once required fields are filled, save the record. You can attach pets to this client right after.',
        placement: 'top',
      },
    ],
  },
  {
    id: 'pets',
    name: 'Register a patient',
    icon: Dog,
    description: 'Add a pet and link it to an owner — works for first-time patients and existing client records.',
    steps: [
      {
        target: 'nav-patients',
        title: 'Patients module',
        body: 'Every pet you treat lives here. Patients always belong to a client.',
        placement: 'right',
        navigateTo: 'patients',
      },
      {
        target: 'pets-register',
        title: 'Register a patient',
        body: 'Click here to add a new pet. You will pick the owner first, then enter the pet details.',
        placement: 'bottom',
      },
      {
        target: 'pet-form-owner',
        title: 'Find the owner first',
        body: 'Start by searching the client by name, phone, or ID, then select them. As soon as you pick the owner, their existing pets appear below to choose from — and the patient form opens so you can register a new one. If the owner isn\'t in the system yet, register the client first.',
        placement: 'bottom',
        navigateTo: 'register-pet',
        waitMs: 200,
      },
      {
        target: 'pet-form-name',
        title: 'Pet details',
        body: 'These patient fields capture the pet — name, gender, species & breed, birth date and weight. (We linked a sample owner so you can see them; in a real entry they appear once you pick an owner above.)',
        placement: 'top',
        awaitInteraction: true,
      },
      {
        target: 'pet-form-microchip',
        title: 'Microchip & tag',
        body: 'Record the microchip and tattoo/tag numbers — these are how lost pets get matched back to this record.',
        placement: 'top',
        optional: true,
      },
      {
        target: 'pet-form-photo',
        title: 'Passport photo',
        body: 'Upload a clear photo for the pet passport and quick visual identification at the front desk.',
        placement: 'top',
        optional: true,
      },
      {
        target: 'pet-form-submit',
        title: 'Save the patient',
        body: 'Save once the form is filled. You can book an appointment for this pet straight away.',
        placement: 'top',
        optional: true,
      },
    ],
  },
  {
    id: 'appointments',
    name: 'Book an appointment',
    icon: CalendarClock,
    description: 'Schedule a visit — pick a client and pet, build the service list, assign staff, and confirm a time slot.',
    steps: [
      {
        target: 'nav-appointments',
        title: 'Appointments module',
        body: 'All visits — scheduled, in-progress, completed — show up here. Use it as your daily schedule view.',
        placement: 'right',
        navigateTo: 'appointments',
      },
      {
        target: 'appointments-new',
        title: 'Start a new visit',
        body: 'Click here to book a new appointment. Walk-ins use the same flow.',
        placement: 'bottom',
      },
      {
        target: 'appointment-client',
        title: 'Pick a client & pet',
        body: 'Search by name or phone, then pick which pet the visit is for. The patient list appears once a client is selected.',
        placement: 'bottom',
        navigateTo: 'new-appointment',
        waitMs: 200,
      },
      {
        target: 'appointment-services',
        title: 'Build the visit workflow',
        body: 'Pick a client & pet above first — the visit workflow appears once a client is selected. Then add service categories, services, prices, staff, and medications.',
        placement: 'top',
        awaitInteraction: true,
      },
      {
        target: 'appointment-scheduling',
        title: 'Lead staff, date & time',
        body: 'Assign a lead vet, choose the date and time slot, and toggle House Call for off-site visits.',
        placement: 'left',
      },
      {
        target: 'appointment-estimate',
        title: 'Estimated bill',
        body: 'This total updates live as you add services and medications, so you can quote the client before confirming.',
        placement: 'left',
      },
      {
        target: 'appointment-submit',
        title: 'Confirm the booking',
        body: 'When the details look right, confirm to book the visit. It then shows up on the appointments schedule.',
        placement: 'top',
      },
    ],
  },
];
