import { Users, Dog, CalendarClock, Stethoscope, UserCog, PawPrint } from 'lucide-react';
import type { Tour } from '../../../../contexts/TourContext';

export const TOURS: Tour[] = [
  {
    id: 'clients',
    name: 'Register a client',
    icon: Users,
    description: 'Walk through every part of the client record — from names to GPS, credit limits, and notes.',
    steps: [
      {
        target: 'nav-clients',
        title: 'Clients live here',
        body: 'The Clients module holds every pet owner. Click the sidebar entry to open it.',
        placement: 'right',
        navigateTo: 'clients',
      },
      {
        target: 'clients-register',
        title: 'Register a new client',
        body: 'Use this button to start a fresh client record. You can also bulk-import from CSV later.',
        placement: 'bottom',
      },
      {
        target: 'client-form-firstname',
        title: 'Names go here',
        body: 'First name + surname are required. Title and second name are optional but helpful for greetings on invoices.',
        placement: 'bottom',
        navigateTo: 'register-client',
        waitMs: 200,
      },
      {
        target: 'client-form-contact',
        title: 'How to reach them',
        body: 'Email and phone power appointment reminders, invoices, and the in-app messaging thread for this client.',
        placement: 'bottom',
      },
      {
        target: 'client-form-demographics',
        title: 'Gender, region & birthday',
        body: 'Region tailors greetings and reporting; date of birth lets you spot long-standing clients and send birthday notes.',
        placement: 'top',
      },
      {
        target: 'client-form-address',
        title: 'Street address',
        body: 'The physical address — estate / road / town. It prints on invoices and is the starting point for house-call visits, so be as specific as you can (e.g. "Westlands, Nairobi").',
        placement: 'top',
      },
      {
        target: 'client-form-location',
        title: 'Pin them on the map (GPS)',
        body: 'Go beyond the street: drop a pin on the map, type exact latitude/longitude, or hit "Use My Location". These precise coordinates power house-call routing and area reports — the street address alone can\'t.',
        placement: 'left',
      },
      {
        target: 'client-form-risk',
        title: 'Risk & credit',
        body: 'Flag the client type, set a max debt ceiling, and score their payment risk — this drives credit warnings at checkout.',
        placement: 'left',
        optional: true,
      },
      {
        target: 'client-form-notes',
        title: 'Internal notes',
        body: 'Private reminders only staff can see — allergies to handling, preferred vet, anything worth flagging next visit.',
        placement: 'top',
        optional: true,
      },
      {
        target: 'client-form-submit',
        title: 'Save the client',
        body: 'Once required fields are filled, save the record. You can attach pets to this client right after.',
        placement: 'top',
      },
    ],
  },
  {
    id: 'pets',
    name: 'Register a patient',
    icon: Dog,
    description: 'Add a pet and link it to an owner — works for first-time patients and existing client records.',
    steps: [
      {
        target: 'nav-patients',
        title: 'Patients module',
        body: 'Every pet you treat lives here. Patients always belong to a client.',
        placement: 'right',
        navigateTo: 'patients',
      },
      {
        target: 'pets-register',
        title: 'Register a patient',
        body: 'Click here to add a new pet. You will pick the owner first, then enter the pet details.',
        placement: 'bottom',
      },
      {
        target: 'pet-form-owner',
        title: 'Find the owner first',
        body: 'Start by searching the client by name, phone, or ID, then select them. As soon as you pick the owner, their existing pets appear below to choose from — and the patient form opens so you can register a new one. If the owner isn\'t in the system yet, register the client first.',
        placement: 'bottom',
        navigateTo: 'register-pet',
        waitMs: 200,
      },
      {
        target: 'pet-form-name',
        title: 'Pet details',
        body: 'These patient fields capture the pet — name, gender, species & breed, birth date and weight. (We linked a sample owner so you can see them; in a real entry they appear once you pick an owner above.)',
        placement: 'top',
        awaitInteraction: true,
      },
      {
        target: 'pet-form-microchip',
        title: 'Microchip & tag',
        body: 'Record the microchip and tattoo/tag numbers — these are how lost pets get matched back to this record.',
        placement: 'top',
        optional: true,
      },
      {
        target: 'pet-form-photo',
        title: 'Passport photo',
        body: 'Upload a clear photo for the pet passport and quick visual identification at the front desk.',
        placement: 'top',
        optional: true,
      },
      {
        target: 'pet-form-submit',
        title: 'Save the patient',
        body: 'Save once the form is filled. You can book an appointment for this pet straight away.',
        placement: 'top',
        optional: true,
      },
    ],
  },
  {
    id: 'appointments',
    name: 'Book an appointment',
    icon: CalendarClock,
    description: 'Schedule a visit — pick a client and pet, build the service list, assign staff, and confirm a time slot.',
    steps: [
      {
        target: 'nav-appointments',
        title: 'Appointments module',
        body: 'All visits — scheduled, in-progress, completed — show up here. Use it as your daily schedule view.',
        placement: 'right',
        navigateTo: 'appointments',
      },
      {
        target: 'appointments-new',
        title: 'Start a new visit',
        body: 'Click here to book a new appointment. Walk-ins use the same flow.',
        placement: 'bottom',
      },
      {
        target: 'appointment-client',
        title: 'Pick a client & pet',
        body: 'Search by name or phone, then pick which pet the visit is for. The patient list appears once a client is selected.',
        placement: 'bottom',
        navigateTo: 'new-appointment',
        waitMs: 200,
      },
      {
        target: 'appointment-services',
        title: 'Build the visit workflow',
        body: 'Pick a client & pet above first — the visit workflow appears once a client is selected. Then add service categories, services, prices, staff, and medications.',
        placement: 'top',
        awaitInteraction: true,
      },
      {
        target: 'appointment-scheduling',
        title: 'Lead staff, date & time',
        body: 'Assign a lead vet, choose the date and time slot, and toggle House Call for off-site visits.',
        placement: 'left',
      },
      {
        target: 'appointment-estimate',
        title: 'Estimated bill',
        body: 'This total updates live as you add services and medications, so you can quote the client before confirming.',
        placement: 'left',
      },
      {
        target: 'appointment-submit',
        title: 'Confirm the booking',
        body: 'When the details look right, confirm to book the visit. It then shows up on the appointments schedule.',
        placement: 'top',
      },
    ],
  },
  {
    id: 'appointment-workflow',
    name: 'Run an appointment',
    icon: Stethoscope,
    description: 'Work through a visit — patient info, services, medical record, billing and settlement.',
    // Contextual: walks through an open visit, so it only runs on the visit page.
    requiresView: ['appointment-detail'],
    steps: [
      {
        target: 'appt-overview',
        title: 'Visit overview',
        body: 'The top of every visit: who the patient is, the owner, the clinic, the total bill, and a progress bar that fills as you complete the work.',
        placement: 'bottom',
      },
      {
        target: 'appt-patient',
        title: 'Patient & owner',
        body: 'Quick reference for the pet and their owner. The "Profile" links jump straight to the full patient or client record.',
        placement: 'bottom',
      },
      {
        target: 'appt-services',
        title: 'Services & tasks',
        body: 'Every service on this visit, grouped by category. Tick tasks off as you go and add extra services with "Add Service" until the visit is finalized.',
        placement: 'right',
      },
      {
        target: 'appt-billing',
        title: 'Billing',
        body: 'The grand total and payment status live here. Once the visit is finalized you settle the bill from this card.',
        placement: 'left',
      },
      {
        target: 'appt-followup',
        title: 'Follow-up visits',
        body: 'Link this visit to a previous or next appointment, or schedule a follow-up to keep the treatment chain connected.',
        placement: 'left',
        optional: true,
      },
      {
        target: 'appt-tabs',
        title: 'Record, medications, invoice & receipt',
        body: 'Switch between the diagnostic record, prescribed medications, the invoice, and (once paid) the receipt — all for this visit.',
        placement: 'top',
      },
      {
        target: 'appt-actions',
        title: 'Finalize & settle',
        body: 'When all tasks are done, finalize the visit, then settle the bill from this floating action button. It changes depending on where the visit is in the workflow.',
        placement: 'left',
        optional: true,
      },
    ],
  },
  {
    id: 'client-details',
    name: 'Manage a client',
    icon: UserCog,
    description: 'Everything on a client record — profile, pets, appointment history and portal access.',
    // Contextual: walks through an open client profile.
    requiresView: ['client-profile'],
    steps: [
      {
        target: 'client-stats',
        title: 'Client at a glance',
        body: 'A quick snapshot of this client: total and completed appointments, what is upcoming, and either their average spend or last visit.',
        placement: 'bottom',
      },
      {
        target: 'client-quickaccess',
        title: 'Scheduled visits',
        body: 'Any upcoming appointments for this client\'s pets show here — jump straight into the visit workflow with one click.',
        placement: 'bottom',
        optional: true,
      },
      {
        target: 'client-identity',
        title: 'Identity profile',
        body: 'The full client record — names, contact details, address and demographics. This is the source of truth for invoices and reminders.',
        placement: 'top',
      },
      {
        target: 'client-edit',
        title: 'Edit the record',
        body: 'Toggle edit mode to update any of the client\'s details, then save your changes.',
        placement: 'left',
        optional: true,
      },
      {
        target: 'client-invite',
        title: 'Invite to the portal',
        body: 'Email the client an invite to the pet-owner portal, where they can view their pets, appointments and records themselves.',
        placement: 'bottom',
        optional: true,
      },
      {
        target: 'client-tabs',
        title: 'Switch between sections',
        body: 'Move between the client\'s pets, appointment history, medical history, discounts and messaging from these tabs.',
        placement: 'bottom',
      },
    ],
  },
  {
    id: 'pet-details',
    name: 'Patient record',
    icon: PawPrint,
    description: 'A patient at a glance — details, vaccines, visit history and medical notes.',
    // Contextual: walks through an open patient profile.
    requiresView: ['pet-profile'],
    steps: [
      {
        target: 'pet-stats',
        title: 'Visit summary',
        body: 'A quick count of this patient\'s visits — total, completed and upcoming — so you can gauge their history at a glance.',
        placement: 'bottom',
      },
      {
        target: 'pet-vaccines',
        title: 'Vaccine status',
        body: 'How many vaccinations this patient has on record, and whether any are due. Open the Immunization tab for the full passport.',
        placement: 'bottom',
      },
      {
        target: 'pet-upcoming',
        title: 'Upcoming appointment',
        body: 'If this patient has a scheduled visit, it appears here — jump straight into the workflow to start treating them.',
        placement: 'bottom',
        optional: true,
      },
      {
        target: 'pet-details',
        title: 'Patient details',
        body: 'The core record — name, species, breed, gender, birth date, weight and microchip. This identifies the pet across the system.',
        placement: 'top',
      },
      {
        target: 'pet-edit',
        title: 'Edit the record',
        body: 'Toggle edit mode to update the patient\'s details, then save your changes.',
        placement: 'left',
        optional: true,
      },
      {
        target: 'pet-tabs',
        title: 'Switch between sections',
        body: 'Move between immunization, appointments, visit history, transactions and the outreach log from these tabs.',
        placement: 'bottom',
      },
    ],
  },
];
